#!/bin/bash
tag="$1"
if [ -z "${tag}" ]; then 
  echo "Usage: $0 <tag>"
  exit
else
  shift
fi
git-buildpackage --git-upstream-tag="${tag}" --git-upstream-branch=master --git-debian-branch=ubuntu/precise --git-upstream-tree=tag -S $@

